# Dukat: Open Source AI Assistant v0.3.1
# Guidelines for building a self-improving AI assistant with DSPy

# Core Principles
- Open Source: Use only open source models and packages
- Local-First: Run everything locally without external API dependencies
- Self-Improving: Implement mechanisms to learn and improve over time
- Quality-Focused: Prioritize automated testing, documentation, and code quality
- Asynchronous: Leverage async processing for responsive performance
- Modular: Build with a plugin architecture for extensibility

# Key Documentation Files
- README.md: Project overview and getting started guide
- PLANNING.md: Development roadmap and architecture
- TASKS.md: Current development tasks and progress
- TESTING.md: Testing approach, coverage, and next steps

# Technology Stack
- Core Framework: DSPy for LLM programming and optimization
- Model Hosting: Ollama for local model inference
- Vector Storage: ChromaDB/FAISS for knowledge and memory
- Development: Poetry, Pytest, Sphinx, Black, Ruff, Mypy, Pre-commit
- Interface: Gradio/Streamlit (web), Rich (terminal)

# Current Development Focus
1. Fix integration tests for memory systems
2. Develop async processing capabilities
3. Create web interface with Gradio
4. Implement task queue system
5. Improve error handling and resilience

# Code Quality Standards
- Documentation: Google-style docstrings with type hints
- Testing: >90% test coverage with unit, integration, and e2e tests
- Linting: Black for formatting, Ruff for linting, Mypy for type checking
- Pre-commit: Automated checks for all code changes

# Development Workflow
- Documentation-Driven: Document interfaces before implementation
- Test-Driven Development: Write tests before implementation
- Implementation Loop: Implement code, test, and document iteratively
- Regular Optimization: Periodically optimize prompts and weights
- Adapt Tests to Code: Adjust tests to match code capabilities rather than downgrading code to pass tests

# Last Updated: 2025-04-23
