version: 2.0.0
project: augment-adam
description: Guidelines for the Augment Adam project

# Project Status
project_status:
  status: active
  phase: development
  next_milestone: "v1.0.0 Release"
  last_updated: "2023-11-15"
  current_focus: "Testing and documentation improvements"

# Development Priorities
priorities:
  current:
    - Testing improvements with focus on memory system and context engine
    - CI/CD pipeline enhancements for faster feedback
    - Documentation refinement with emphasis on developer guides
    - Monte Carlo methods test coverage improvement
  upcoming:
    - Performance optimization for large-scale deployments
    - Additional memory backends (Pinecone, Weaviate)
    - Enhanced agent coordination patterns
    - Parallel processing optimizations
    - Workflow execution components

# Core Components
components:
  - name: Tagging System
    description: Hierarchical tagging system with registry isolation
    status: stable
    tag: core.tagging

  - name: Memory System
    description: Vector and graph-based memory with multiple backends
    status: stable
    tag: core.memory

  - name: Context Engine
    description: Intelligent context management and retrieval
    status: stable
    tag: core.context

  - name: Template Engine
    description: Powerful template engine with tagging support
    status: stable
    tag: core.template

  - name: Agent Coordination
    description: Coordinate multiple agents to work together
    status: stable
    tag: core.agent.coordination

  - name: Monte Carlo Techniques
    description: Probabilistic modeling and sampling
    status: stable
    tag: core.monte_carlo

  - name: Testing Framework
    description: Comprehensive test suite and testing utilities
    status: improving
    tag: core.testing

  - name: Documentation System
    description: Comprehensive documentation with tagging
    status: stable
    tag: core.documentation

# Code Style Guidelines
code_style:
  docstrings: google
  type_hints: required
  line_length: 88
  formatting: black
  linting: ruff
  imports: isort
  tagging: required

# Testing Guidelines
testing:
  unit_tests: required
  integration_tests: required
  e2e_tests: recommended
  coverage_target: 80%
  pre_commit: required
  ci_integration: required
  test_isolation: required
  tag_registry_isolation: required
  priority_components:
    - memory_system
    - context_engine
    - monte_carlo_methods
    - parallel_processing
    - async_executor
    - workflow_execution
  test_generation: use_test_templates_when_possible
  test_documentation: update_tests_TASKS_after_each_atomic_change
  test_approach: focus_on_actual_functionality_not_frivolous_tests
  incremental_development: acceptable_for_test_coverage

# Git Guidelines
git:
  branch_naming: feature/fix/refactor-description
  commit_message: conventional
  pr_template: required
  code_review: required
  branch_protection: enabled
  ci_checks: required

# CI/CD Guidelines
ci_cd:
  pre_commit_hooks:
    - linting
    - formatting
    - type_checking
    - unit_tests
  github_actions:
    - test
    - pre-commit
    - coverage
  branch_protection:
    - require_ci_pass
    - require_review
    - no_force_push

# Documentation Structure
documentation:
  system:
    tag: documentation.system
    description: Documentation about the documentation system itself
  architecture:
    tag: documentation.architecture
    description: High-level architecture documentation
  user_guides:
    tag: documentation.user
    description: End-user documentation
  developer_guides:
    tag: documentation.developer
    description: Documentation for developers
  api:
    tag: documentation.api
    description: API reference documentation

# Tagging Guidelines
tagging:
  format: hierarchical.dot.notation
  required_categories:
    - core
    - memory
    - agent
    - context
    - template
    - testing
    - documentation
  registry_isolation:
    testing: required
    development: recommended

# Memory System Guidelines
memory:
  backends:
    - faiss
    - neo4j
    - redis
    - chroma
  vector_dimensions: 1536
  default_backend: faiss
  persistence: required
  thread_safety: required
  testing_priorities:
    - vector_memory_integration
    - graph_memory_integration
    - hybrid_memory_systems
    - memory_persistence
    - memory_indexing
  utility_classes:
    - memory_manager
    - memory_factory
    - memory_connector

# Agent Guidelines
agents:
  coordination_patterns:
    - orchestrator
    - peer_to_peer
    - hierarchical
  communication:
    encryption: recommended
    validation: required
  versioning: required
  discovery: dynamic

# Workflow Execution Guidelines
workflow:
  components:
    - workflow: task_definition_and_dependencies
    - workflow_executor: execution_orchestration
    - workflow_task: atomic_task_unit
    - task_dependency: dependency_management
  execution_modes:
    - sequential
    - parallel
    - conditional
  error_handling: required
  monitoring: required

# Utility Components
utilities:
  resource_management:
    - resource_monitor: system_resource_tracking
    - resource_throttler: prevent_overutilization
  result_handling:
    - result_aggregator: combine_multiple_results
    - error_handler: graceful_error_management

# Development Workflow
development_workflow:
  task_tracking: github_compatible_TASKS_files
  task_limit: maximum_10_tasks_per_file
  task_organization: one_TASKS_file_per_directory
  planning_reference: all_tasks_must_reference_PLANNING_items
  testing_reference: all_tasks_must_reference_TESTING_items
