version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .devcontainer folder
      - ..:/workspace:cached

      # Mount Docker socket for Docker-in-Docker
      - /var/run/docker.sock:/var/run/docker.sock

      # Mount existing volumes for large files and models
      - OllamaModels:/root/.ollama:cached
      - model-cache:/workspace/.cache/models:cached
      - huggingface-cache:/workspace/.cache/huggingface:cached

      # Mount Git config
      - ~/.gitconfig:/home/vscode/.gitconfig:ro

    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity

    # Forward ports for services
    ports:
      - "8888:8888"  # Jupyter
      - "11434:11434"  # Ollama

    # Set environment variables
    environment:
      - PYTHONPATH=/workspace
      - HF_HOME=/workspace/.cache/huggingface

    # Use the "remoteUser" property in devcontainer.json to specify a non-root user
    # Commented out to let the Dockerfile and devcontainer.json handle user setup
    # user: vscode

    # GPU configuration - commented out as no NVIDIA GPU detected
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  # Define named volumes
  OllamaModels:
    external: true
  model-cache:
    external: false  # Will be created if it doesn't exist
  huggingface-cache:
    external: false  # Will be created if it doesn't exist
