name: CD

on:
  release:
    types: [created]

jobs:
  # All jobs are temporarily disabled for branch cleanup
  dummy-job:
    name: Placeholder Job (CD Disabled)
    runs-on: ubuntu-latest

    steps:
    - name: Placeholder step
      run: echo "CD pipeline is temporarily disabled for branch cleanup"
