name: Scheduled Tests

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: "0 2 * * *"

jobs:
  full-test-suite:
    name: Full Test Suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
poetry install --with dev

      - name: Run unit tests
        run: pytest tests/unit -v --cov=augment_adam --cov-report=xml

      - name: Run integration tests
        run: pytest tests/integration -v

      - name: Run compatibility tests
        run: pytest tests/compatibility -v

      - name: Run performance tests
        run: pytest tests/performance -v

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

      - name: Notify on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ci-alerts
          SLACK_COLOR: danger
          SLACK_TITLE: Scheduled Tests Failed
          SLACK_MESSAGE: "Scheduled tests failed on main branch. Please check the logs."
          SLACK_FOOTER: "Augment Adam CI/CD"
